---
- name: Install wireguard
  ansible.builtin.package:
    name: wireguard-tools
    state: present

- name: Install NodeJS
  ansible.builtin.include_role:
    name: geerlingguy.nodejs
  vars:
    nodejs_version: "{{ wiregaurd_easy_nodejs_version }}"
  when: not (wiregaurd_easy_skip_nodejs | bool)
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create wg-easy user
  ansible.builtin.user:
    name: "{{ wiregaurd_easy_user }}"
    comment: wg-easy User
    state: present
    password: !
    system: true
    home: "/home/{{ wiregaurd_easy_user }}"
    create_home: true
    shell: /sbin/nologin
    password_lock: true
  # Always create the user, so that the following steps can succeed
  check_mode: false

- name: Ensure config path file permissions
  ansible.builtin.file:
    state: directory
    path: "{{ wireguard_easy_config_path }}"
    owner: "root"
    group: "{{ wiregaurd_easy_user }}"
