---
- name: Install wireguard and sudo
  ansible.builtin.package:
    name:
      - "{{ (wireguard_easy_user == 'root') | ternary(omit, 'sudo') }}"
      - wireguard-tools
    state: present

- name: Create wg-easy user
  ansible.builtin.user:
    name: "{{ wireguard_easy_user }}"
    comment: wg-easy User
    state: present
    password: !
    system: true
    home: "/home/{{ wireguard_easy_user }}"
    create_home: true
    shell: /sbin/nologin
    password_lock: true
  # Always create the user, so that the following steps can succeed
  check_mode: false
  when: wireguard_easy_user != 'root'

- name: Allow WireGuard User passwordless sudo
  ansible.builtin.template:
    src: sudo/01-wireguard.j2
    dest: /etc/sudoers.d/01-{{ wireguard_easy_user }}
  when: wireguard_easy_user != 'root'

- name: Ensure config path file permissions
  ansible.builtin.file:
    state: directory
    path: "{{ wireguard_easy_config_path }}"
    owner: "root"
    group: "{{ wireguard_easy_user }}"
    mode: "g+rwx"
